# Generated by Django 4.2.6 on 2023-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_hobby_options_alter_profile_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caste',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(null=True, related_name='profiles', to='app.hobby'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sect',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
