# Generated by Django 4.2.6 on 2023-10-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_caste_name_alter_hobby_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caste',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(related_name='profiles', to='app.hobby'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sect',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
