# Generated by Django 4.2.6 on 2023-10-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
